spring:
  redis:
    host: 10.10.10.40
    port: 6379
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
zooClientIp: 101.133.149.61:2181